version: '3'
services:
        frontend:
                image: vattenhub_client:latest
                ports:
                 - '4200:4200'
        backend:
                image: vattenhub_server:latest
                ports: 
                 - "8080:8080"
                depends_on:
                 - mongo
        mongo:
                image: mongo:latest
                ports: 
                 - "27017:27017"
                volumes: 
                 - ./data/db:/data/db
                command: --smallfiles
