version: '3'
services:
        frontend:
                build:
                        context: ./client/portal-app
                ports:
                 - '4200:4200'
        backend:
                build:
                        context: ./server
                ports: 
                 - "8080:8080"
                depends_on:
                 - mongo
        mongo:
                image: mongo:latest
                ports: 
                 - "27017:27017"
                volumes: 
                 - ./data/db:/data/db
                command: --smallfiles
